version: "3"

services:
  arrayed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arrayed
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: arrayed
    volumes:
      - ./:/var/www/html
    networks:
      - arrayed-network

#Docker Networks
networks:
  arrayed-network:
    driver: bridge